on: push
name: Build and deploy GH Pages
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          CHECK_LINKS: true

  build:
    environment: main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
